package com.cordys.coe.ac.emailio.localization;

import com.eibus.localization.message.Message;
import com.eibus.localization.message.MessageSet;

/**
 * This code is generated by running com.cordys.coe.cep.wizards.localization.CoEMessageGenerator.
 */
public class ActionExceptionMessages
{
    /**
     * Holds the definition of the message set.
     */
    public static final MessageSet MESSAGE_SET = MessageSet.getMessageSet("com.cordys.coe.ac.emailio.exception.ActionException");

    /**
     * Holds the definition of the message with ID AE_ERROR_SENDING_THE_SOAP_REQUEST. Message text:
     * Error sending the soap request.
     */
    public static final Message AE_ERROR_SENDING_THE_SOAP_REQUEST = MESSAGE_SET.getMessage("AE_ERROR_SENDING_THE_SOAP_REQUEST");
    /**
     * Holds the definition of the message with ID AE_ERROR_SEND_MAIL_ACTION. Message text: Error
     * sending the mail action
     */
    public static final Message AE_ERROR_SEND_MAIL_ACTION = MESSAGE_SET.getMessage("AE_ERROR_SEND_MAIL_ACTION");
    /**
     * Holds the definition of the message with ID AE_ERROR_EXECUTING_CUSTOMACTION. Message text:
     * Error executing CustomAction
     */
    public static final Message AE_ERROR_EXECUTING_CUSTOMACTION = MESSAGE_SET.getMessage("AE_ERROR_EXECUTING_CUSTOMACTION");
}
