

 /**
 * Copyright 2007 Cordys R&D B.V. 
 * 
 * This file is part of the Cordys Email IO Connector. 
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.cordys.coe.ac.emailio.localization;

import com.eibus.localization.message.Message;
import com.eibus.localization.message.MessageSet;

/**
 * This code is generated by running com.cordys.coe.cep.wizards.localization.CoEMessageGenerator.
 */
public class OutboundEmailExceptionMessages
{
    /**
     * Holds the definition of the message set.
     */
    public static final MessageSet MESSAGE_SET = MessageSet.getMessageSet("com.cordys.coe.ac.emailio.exception.OutboundEmailException");

    /**
     * Holds the definition of the message with ID OEE_COMP_ATTACHMENT_NAME_IS_NOT_GIVEN. Message
     * text: Attachment name is not given.
     */
    public static final Message OEE_COMP_ATTACHMENT_NAME_IS_NOT_GIVEN = MESSAGE_SET.getMessage("OEE_COMP_ATTACHMENT_NAME_IS_NOT_GIVEN");
    /**
     * Holds the definition of the message with ID OEE_COULD_NOT_FIND_A_CERTIFICATE_FOR_RECIPIENT_0.
     * Message text: Could not find a certificate for recipient {0}
     */
    public static final Message OEE_COULD_NOT_FIND_A_CERTIFICATE_FOR_RECIPIENT_0 = MESSAGE_SET
                                                                                   .getMessage("OEE_COULD_NOT_FIND_A_CERTIFICATE_FOR_RECIPIENT_0");
    /**
     * Holds the definition of the message with ID
     * OEE_FOR_A_MULTIPART_EITHER_NESTED_MULTIPART_SHOULD_BE_DEFINED_OR_DATA_SHOULD_BE_PRESENT.
     * Message text: For a multipart either nested multipart should be defined OR data should be
     * present.
     */
    public static final Message OEE_FOR_A_MULTIPART_EITHER_NESTED_MULTIPART_SHOULD_BE_DEFINED_OR_DATA_SHOULD_BE_PRESENT = MESSAGE_SET
                                                                                                                          .getMessage("OEE_FOR_A_MULTIPART_EITHER_NESTED_MULTIPART_SHOULD_BE_DEFINED_OR_DATA_SHOULD_BE_PRESENT");
    /**
     * Holds the definition of the message with ID OEE_ONE_OF_THE_TAGS_0_OR_1_SHOULD_BE_SPECIFIED.
     * Message text: One of the tags {0} or {1} should be specified.
     */
    public static final Message OEE_ONE_OF_THE_TAGS_0_OR_1_SHOULD_BE_SPECIFIED = MESSAGE_SET
                                                                                 .getMessage("OEE_ONE_OF_THE_TAGS_0_OR_1_SHOULD_BE_SPECIFIED");
    /**
     * Holds the definition of the message with ID
     * OEE_ONLY_ONE_OF_THE_TAGS_0_AND_1_SHOULD_BE_SPECIFIED_FOR_THE_SEND_MAIL_DATA. Message text:
     * Only one of the tags {0} and {1} should be specified for the send mail data
     */
    public static final Message OEE_ONLY_ONE_OF_THE_TAGS_0_AND_1_SHOULD_BE_SPECIFIED_FOR_THE_SEND_MAIL_DATA = MESSAGE_SET
                                                                                                              .getMessage("OEE_ONLY_ONE_OF_THE_TAGS_0_AND_1_SHOULD_BE_SPECIFIED_FOR_THE_SEND_MAIL_DATA");
    /**
     * Holds the definition of the message with ID
     * OEE_THE_TAG_DETAIL_MUST_BE_SPECIFIED_FOR_THE_MAIL_DATA. Message text: The tag detail must be
     * specified for the mail data.
     */
    public static final Message OEE_THE_TAG_DETAIL_MUST_BE_SPECIFIED_FOR_THE_MAIL_DATA = MESSAGE_SET
                                                                                         .getMessage("OEE_THE_TAG_DETAIL_MUST_BE_SPECIFIED_FOR_THE_MAIL_DATA");
    /**
     * Holds the definition of the message with ID OEE_THE_TAG_SOURCE_MUST_BE_SET_FOR_THE_MAIL_DATA.
     * Message text: The tag source must be set for the mail data
     */
    public static final Message OEE_THE_TAG_SOURCE_MUST_BE_SET_FOR_THE_MAIL_DATA = MESSAGE_SET
                                                                                   .getMessage("OEE_THE_TAG_SOURCE_MUST_BE_SET_FOR_THE_MAIL_DATA");
    /**
     * Holds the definition of the message with ID
     * OEE_AT_LEAST_1_RECIPIENT_ADDRESS_MUST_BE_SPECIFIED. Message text: At least 1 recipient
     * address must be specified.
     */
    public static final Message OEE_AT_LEAST_1_RECIPIENT_ADDRESS_MUST_BE_SPECIFIED = MESSAGE_SET
                                                                                     .getMessage("OEE_AT_LEAST_1_RECIPIENT_ADDRESS_MUST_BE_SPECIFIED");
    /**
     * Holds the definition of the message with ID
     * OEE_COULD_NOT_FIND_A_PRIVATE_KEY_FOR_EMAIL_ADDRESS_0. Message text: Could not find a private
     * key for email address {0}
     */
    public static final Message OEE_COULD_NOT_FIND_A_PRIVATE_KEY_FOR_EMAIL_ADDRESS_0 = MESSAGE_SET
                                                                                       .getMessage("OEE_COULD_NOT_FIND_A_PRIVATE_KEY_FOR_EMAIL_ADDRESS_0");
    /**
     * Holds the definition of the message with ID OEE_COULD_NOT_FIND_FILE_0. Message text: Could
     * not find file {0}
     */
    public static final Message OEE_COULD_NOT_FIND_FILE_0 = MESSAGE_SET.getMessage("OEE_COULD_NOT_FIND_FILE_0");
    /**
     * Holds the definition of the message with ID
     * OEE_COULD_NOT_FIND_THE_EMAIL_ADDRESS_IN_THE_MAIL_MESSAGE. Message text: Could not find the
     * email address in the mail message
     */
    public static final Message OEE_COULD_NOT_FIND_THE_EMAIL_ADDRESS_IN_THE_MAIL_MESSAGE = MESSAGE_SET
                                                                                           .getMessage("OEE_COULD_NOT_FIND_THE_EMAIL_ADDRESS_IN_THE_MAIL_MESSAGE");
    /**
     * Holds the definition of the message with ID
     * OEE_COULD_NOT_FIND_THE_PUBLIC_KEY_FOR_THE_EMAIL_ADDRESS_0. Message text: Could not find the
     * public key for the email address {0}
     */
    public static final Message OEE_COULD_NOT_FIND_THE_PUBLIC_KEY_FOR_THE_EMAIL_ADDRESS_0 = MESSAGE_SET
                                                                                            .getMessage("OEE_COULD_NOT_FIND_THE_PUBLIC_KEY_FOR_THE_EMAIL_ADDRESS_0");
    /**
     * Holds the definition of the message with ID OEE_COULD_NOT_READ_FILE_0. Message text: Could
     * not read file {0}
     */
    public static final Message OEE_COULD_NOT_READ_FILE_0 = MESSAGE_SET.getMessage("OEE_COULD_NOT_READ_FILE_0");
    /**
     * Holds the definition of the message with ID OEE_ERROR_CREATING_INTERNET_ADDRESS_FROM_0.
     * Message text: Error creating internet address from {0}
     */
    public static final Message OEE_ERROR_CREATING_INTERNET_ADDRESS_FROM_0 = MESSAGE_SET.getMessage("OEE_ERROR_CREATING_INTERNET_ADDRESS_FROM_0");
    /**
     * Holds the definition of the message with ID OEE_ERROR_CREATING_MIME_MESSAGE_FOR_EMAIL_DATA.
     * Message text: Error creating mime message for email data.
     */
    public static final Message OEE_ERROR_CREATING_MIME_MESSAGE_FOR_EMAIL_DATA = MESSAGE_SET
                                                                                 .getMessage("OEE_ERROR_CREATING_MIME_MESSAGE_FOR_EMAIL_DATA");
    /**
     * Holds the definition of the message with ID OEE_ERROR_ENCRYPTING_THE_MAIL. Message text:
     * Error encrypting the mail
     */
    public static final Message OEE_ERROR_ENCRYPTING_THE_MAIL = MESSAGE_SET.getMessage("OEE_ERROR_ENCRYPTING_THE_MAIL");
    /**
     * Holds the definition of the message with ID
     * OEE_ERROR_GETTING_THE_EMAIL_ADDRESS_OF_THE_SENDER_FROM_THE_MESSAGE. Message text: Error
     * getting the email address of the sender from the message
     */
    public static final Message OEE_ERROR_GETTING_THE_EMAIL_ADDRESS_OF_THE_SENDER_FROM_THE_MESSAGE = MESSAGE_SET
                                                                                                     .getMessage("OEE_ERROR_GETTING_THE_EMAIL_ADDRESS_OF_THE_SENDER_FROM_THE_MESSAGE");
    /**
     * Holds the definition of the message with ID OEE_ERROR_READING_FILE_0. Message text: Error
     * reading file {0}
     */
    public static final Message OEE_ERROR_READING_FILE_0 = MESSAGE_SET.getMessage("OEE_ERROR_READING_FILE_0");
    /**
     * Holds the definition of the message with ID OEE_ERROR_SIGNING_EMAIL_MESSAGE. Message text:
     * Error signing email message
     */
    public static final Message OEE_ERROR_SIGNING_EMAIL_MESSAGE = MESSAGE_SET.getMessage("OEE_ERROR_SIGNING_EMAIL_MESSAGE");
    /**
     * Holds the definition of the message with ID OEE_THE_CONTENT_TYPE_MUST_BE_SET_FOR_MAIL_DATA.
     * Message text: The content type must be set for mail data
     */
    public static final Message OEE_THE_CONTENT_TYPE_MUST_BE_SET_FOR_MAIL_DATA = MESSAGE_SET
                                                                                 .getMessage("OEE_THE_CONTENT_TYPE_MUST_BE_SET_FOR_MAIL_DATA");
    /**
     * Holds the definition of the message with ID OEE_THE_TAG_0_MUST_BE_FILLED. Message text: The
     * tag {0} must be filled
     */
    public static final Message OEE_THE_TAG_0_MUST_BE_FILLED = MESSAGE_SET.getMessage("OEE_THE_TAG_0_MUST_BE_FILLED");
    /**
     * Holds the definition of the message with ID
     * OEE_COULD_NOT_FIND_THE_TAG_0_FOR_THE_EMAIL_ADDRESS. Message text: Could not find the tag {0}
     * for the email address
     */
    public static final Message OEE_COULD_NOT_FIND_THE_TAG_0_FOR_THE_EMAIL_ADDRESS = MESSAGE_SET
                                                                                     .getMessage("OEE_COULD_NOT_FIND_THE_TAG_0_FOR_THE_EMAIL_ADDRESS");
    /**
     * Holds the definition of the message with ID OEE_MISSING_PARAMETER. Message text: Missing
     * parameter {0}
     */
    public static final Message OEE_MISSING_PARAMETER = MESSAGE_SET.getMessage("OEE_MISSING_PARAMETER");
    /**
     * Holds the definition of the message with ID OEE_ERROR_SENDING_0_MESSAGES_USING_SERVER.
     * Message text: {0}: Error sending {1} messages using server {2}:{3}
     */
    public static final Message OEE_ERROR_SENDING_0_MESSAGES_USING_SERVER = MESSAGE_SET.getMessage("OEE_ERROR_SENDING_0_MESSAGES_USING_SERVER");
    /**
     * Holds the definition of the message with ID OEE_COULD_NOT_OBTAIN_A_SMTP_CONNECTION. Message
     * text: Could not obtain a SMTP connection
     */
    public static final Message OEE_COULD_NOT_OBTAIN_A_SMTP_CONNECTION = MESSAGE_SET.getMessage("OEE_COULD_NOT_OBTAIN_A_SMTP_CONNECTION");
}
