/**
 * Copyright 2005 Cordys R&D B.V. 
 * 
 * This file is part of the Cordys SAP Connector. 
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 /**
 * Copyright 2005 Cordys R&D B.V. 
 * 
 * This file is part of the Cordys SAP Connector. 
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 package com.cordys.coe.ac.emailio.localization;

import com.eibus.localization.message.Message;
import com.eibus.localization.message.MessageSet;

/**
 * This code is generated by running com.cordys.coe.cep.wizards.localization.CoEMessageGenerator.
 */
public class TriggerStoreExceptionMessages
{
    /**
     * Holds the definition of the message set.
     */
    public static final MessageSet MESSAGE_SET = MessageSet.getMessageSet("com.cordys.coe.ac.emailio.exception.TriggerStoreException");

    /**
     * Holds the definition of the message with ID TSE_TRIGGER_STORE_CLASS_COULD_NOT_BE_FOUND.
     * Message text: Trigger store class could not be found: {0}
     */
    public static final Message TSE_TRIGGER_STORE_CLASS_COULD_NOT_BE_FOUND = MESSAGE_SET.getMessage("TSE_TRIGGER_STORE_CLASS_COULD_NOT_BE_FOUND");
    /**
     * Holds the definition of the message with ID STETRIGGER_STORE_CLASS_COULD_NOT_BE_INSTANCIATED.
     * Message text: Trigger store class {0} could not be instanciated: {1}
     */
    public static final Message STETRIGGER_STORE_CLASS_COULD_NOT_BE_INSTANCIATED = MESSAGE_SET
                                                                                   .getMessage("STETRIGGER_STORE_CLASS_COULD_NOT_BE_INSTANCIATED");
    /**
     * Holds the definition of the message with ID
     * TSE_SPECIFIED_CLASS_DOES_NOT_IMPLEMENT_ITRIGGERSTORE_0. Message text: Specified class does
     * not implement ITriggerStore: {0}
     */
    public static final Message TSE_SPECIFIED_CLASS_DOES_NOT_IMPLEMENT_ITRIGGERSTORE_0 = MESSAGE_SET
                                                                                         .getMessage("TSE_SPECIFIED_CLASS_DOES_NOT_IMPLEMENT_ITRIGGERSTORE_0");
    /**
     * Holds the definition of the message with ID TSE_NO_CONFIGURATION_NODE_WAS_SPECIFIED. Message
     * text: No configuration node was specified.
     */
    public static final Message TSE_NO_CONFIGURATION_NODE_WAS_SPECIFIED = MESSAGE_SET.getMessage("TSE_NO_CONFIGURATION_NODE_WAS_SPECIFIED");
    /**
     * Holds the definition of the message with ID TSE_NO_TRIGGER_STORE_CLASS_WAS_SPECIFIED. Message
     * text: No trigger store class was specified.
     */
    public static final Message TSE_NO_TRIGGER_STORE_CLASS_WAS_SPECIFIED = MESSAGE_SET.getMessage("TSE_NO_TRIGGER_STORE_CLASS_WAS_SPECIFIED");
    /**
     * Holds the definition of the message with ID FTS_COULD_NOT_DESERIALIZE_TRIGGER. Message text:
     * Could not deserialize trigger: {0}
     */
    public static final Message FTS_COULD_NOT_DESERIALIZE_TRIGGER = MESSAGE_SET.getMessage("FTS_COULD_NOT_DESERIALIZE_TRIGGER");
    /**
     * Holds the definition of the message with ID FTS_DIRECTORY_NOT_VALID. Message text: The
     * working directory exists, but it isn't a directory or can't be written to: {0}
     */
    public static final Message FTS_DIRECTORY_NOT_VALID = MESSAGE_SET.getMessage("FTS_DIRECTORY_NOT_VALID");
    /**
     * Holds the definition of the message with ID FTS_EMPTY_STRINGS_FILENAME. Message text: Empty
     * strings can't be used as file names.
     */
    public static final Message FTS_EMPTY_STRINGS_FILENAME = MESSAGE_SET.getMessage("FTS_EMPTY_STRINGS_FILENAME");
    /**
     * Holds the definition of the message with ID FTS_COULD_NOT_DELETE_TRIGGER_FILE. Message text:
     * Could not delete trigger file: {0}
     */
    public static final Message FTS_COULD_NOT_DELETE_TRIGGER_FILE = MESSAGE_SET.getMessage("FTS_COULD_NOT_DELETE_TRIGGER_FILE");
    /**
     * Holds the definition of the message with ID FTS_EXCEPTION_DURING_TRIGGER_SERIALIZATION.
     * Message text: Unsupported exception during trigger serialization: {0}
     */
    public static final Message FTS_EXCEPTION_DURING_TRIGGER_SERIALIZATION = MESSAGE_SET.getMessage("FTS_EXCEPTION_DURING_TRIGGER_SERIALIZATION");
}
