/**
 * Copyright 2005 Cordys R&D B.V. 
 * 
 * This file is part of the Cordys SAP Connector. 
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 /**
 * Copyright 2005 Cordys R&D B.V. 
 * 
 * This file is part of the Cordys SAP Connector. 
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 package com.cordys.coe.ac.emailio.localization;

import com.eibus.localization.message.Message;
import com.eibus.localization.message.MessageSet;

/**
 * This code is generated by running com.cordys.coe.cep.wizards.localization.CoEMessageGenerator.
 */
public class ActionExceptionMessages
{
    /**
     * Holds the definition of the message set.
     */
    public static final MessageSet MESSAGE_SET = MessageSet.getMessageSet("com.cordys.coe.ac.emailio.exception.ActionException");

    /**
     * Holds the definition of the message with ID AE_ERROR_SENDING_THE_SOAP_REQUEST. Message text:
     * Error sending the soap request.
     */
    public static final Message AE_ERROR_SENDING_THE_SOAP_REQUEST = MESSAGE_SET.getMessage("AE_ERROR_SENDING_THE_SOAP_REQUEST");
    /**
     * Holds the definition of the message with ID AE_ERROR_SEND_MAIL_ACTION. Message text: Error
     * sending the mail action
     */
    public static final Message AE_ERROR_SEND_MAIL_ACTION = MESSAGE_SET.getMessage("AE_ERROR_SEND_MAIL_ACTION");
    /**
     * Holds the definition of the message with ID AE_ERROR_EXECUTING_CUSTOMACTION. Message text:
     * Error executing CustomAction
     */
    public static final Message AE_ERROR_EXECUTING_CUSTOMACTION = MESSAGE_SET.getMessage("AE_ERROR_EXECUTING_CUSTOMACTION");
}
