/**
 * Copyright 2005 Cordys R&D B.V. 
 * 
 * This file is part of the Cordys SAP Connector. 
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 /**
 * Copyright 2005 Cordys R&D B.V. 
 * 
 * This file is part of the Cordys SAP Connector. 
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 package com.cordys.coe.ac.emailio.localization;

import com.eibus.localization.message.Message;
import com.eibus.localization.message.MessageSet;

/**
 * This code is generated by running com.cordys.coe.cep.wizards.localization.CoEMessageGenerator.
 */
public class WsAppUtilExceptionMessages
{
    /**
     * Holds the definition of the message set.
     */
    public static final MessageSet MESSAGE_SET = MessageSet.getMessageSet("com.cordys.coe.ac.emailio.exception.WsAppUtilException");

    /**
     * Holds the definition of the message with ID WAU_ERROR_GETTING_ACCESSCONTROLOBJECT_FOR_USER.
     * Message text: Error getting AccessControlObject for user {0}
     */
    public static final Message WAU_ERROR_GETTING_ACCESSCONTROLOBJECT_FOR_USER = MESSAGE_SET
                                                                                 .getMessage("WAU_ERROR_GETTING_ACCESSCONTROLOBJECT_FOR_USER");
    /**
     * Holds the definition of the message with ID
     * WAU_THE_CONFIGURATION_WITH_NAME_0_COULD_NOT_BE_FOUND. Message text: The configuration with
     * name {0} could not be found.
     */
    public static final Message WAU_THE_CONFIGURATION_WITH_NAME_0_COULD_NOT_BE_FOUND = MESSAGE_SET
                                                                                       .getMessage("WAU_THE_CONFIGURATION_WITH_NAME_0_COULD_NOT_BE_FOUND");
    /**
     * Holds the definition of the message with ID WAU_THE_NAME_OF_THE_COMPONENT_MUST_BE_SET.
     * Message text: The name of the component must be set.
     */
    public static final Message WAU_THE_NAME_OF_THE_COMPONENT_MUST_BE_SET = MESSAGE_SET.getMessage("WAU_THE_NAME_OF_THE_COMPONENT_MUST_BE_SET");
    /**
     * Holds the definition of the message with ID WAU_ERROR_CREATING_CONFIGURATION_WITH_NAME.
     * Message text: Error creating configuration with name {0}
     */
    public static final Message WAU_ERROR_CREATING_CONFIGURATION_WITH_NAME = MESSAGE_SET.getMessage("WAU_ERROR_CREATING_CONFIGURATION_WITH_NAME");
}
