PRINT 'Creating table EMAIL_BOX...'
GO
CREATE TABLE [dbo].[EMAIL_BOX](
	[EMAILBOX_ID] [nvarchar] (50) NOT NULL  ,
	[BOX_NAME] [nvarchar] (50) NOT NULL  ,
	[HOST] [nvarchar] (150) NOT NULL  ,
	[BOX_TYPE] [nvarchar] (50) NOT NULL  ,
	[CONFIGURATION] [ntext] NULL 
) ON [PRIMARY]
GO

PRINT 'Creating table CONTEXT_CONTAINER...'
GO
CREATE TABLE [dbo].[CONTEXT_CONTAINER](
	[CONTEXT_CONTAINER_ID] [nvarchar] (50) NOT NULL  ,
	[EMAILBOX] [nvarchar] (50) NOT NULL  ,
	[PROCESSING_STATUS] [nvarchar] (30) NOT NULL  ,
	[STATUS_INFORMATION] [ntext] NULL  ,
	[TRIGGER_DEFINITION] [ntext] NULL  ,
	[CREATE_DATE] [datetime] NOT NULL  ,
	[STATUS_CHANGE_DATE] [datetime] NOT NULL  ,
	[COMPLETE_DATE] [datetime] NULL 
) ON [PRIMARY]
GO

PRINT 'Creating table EMAIL...'
GO
CREATE TABLE [dbo].[EMAIL](
	[EMAIL_ID] [nvarchar] (50) NOT NULL  ,
	[CONTEXT_CONTAINER] [nvarchar] (50) NOT NULL  ,
	[SEQUENCE_ID] [bigint] NOT NULL  Default (0) ,
	[SEND_DATE] [datetime] NULL  ,
	[RECEIVE_DATE] [datetime] NULL  ,
	[FROM_ADDRESS] [nvarchar] (200) NULL  ,
	[TO_ADDRESS] [nvarchar] (200) NULL  ,
	[SUBJECT] [nvarchar] (200) NULL  ,
	[CONTENT] [ntext] NULL 
) ON [PRIMARY]
GO

PRINT 'Creating table TRIGGER_STORE...'
GO
CREATE TABLE [dbo].[TRIGGER_STORE](
	[TRIGGER_ID] [nvarchar] (50) NOT NULL  ,
	[EMAILBOX] [nvarchar] (50) NOT NULL  ,
	[TRIGGER_NAME] [nvarchar] (150) NULL  ,
	[CONTENT] [ntext] NULL 
) ON [PRIMARY]
GO

PRINT 'Creating indices for table EMAIL_BOX...'
GO
ALTER TABLE [dbo].[EMAIL_BOX] WITH NOCHECK ADD
	CONSTRAINT [PK_EMAIL_BOX] PRIMARY KEY  CLUSTERED
	(
		[EMAILBOX_ID] 
	) ON [PRIMARY]
	,
	CONSTRAINT [IX_EMAIL_BOX] UNIQUE NONCLUSTERED 
	(
		[BOX_NAME] 
	) ON [PRIMARY]
GO

PRINT 'Creating indices for table CONTEXT_CONTAINER...'
GO
ALTER TABLE [dbo].[CONTEXT_CONTAINER] WITH NOCHECK ADD
	CONSTRAINT [PK_CONTEXT_CONTAINER] PRIMARY KEY  CLUSTERED
	(
		[CONTEXT_CONTAINER_ID] 
	) ON [PRIMARY]
GO

 CREATE INDEX [IX_CONTEXT_CONTAINER_EMAIL_BOX] ON [dbo].[CONTEXT_CONTAINER]([EMAILBOX]) ON [PRIMARY]
GO

 CREATE INDEX [IX_CONTEXT_CONTAINER_PROCESSING_STATUS] ON [dbo].[CONTEXT_CONTAINER]([PROCESSING_STATUS]) ON [PRIMARY]
GO

PRINT 'Creating indices for table EMAIL...'
GO
ALTER TABLE [dbo].[EMAIL] WITH NOCHECK ADD
	CONSTRAINT [PK_EMAIL_DETAIL] PRIMARY KEY  CLUSTERED
	(
		[EMAIL_ID] 
	) ON [PRIMARY]
GO

PRINT 'Creating indices for table TRIGGER_STORE...'
GO
ALTER TABLE [dbo].[TRIGGER_STORE] WITH NOCHECK ADD
	CONSTRAINT [PK_TRIGGER_STORE] PRIMARY KEY  CLUSTERED
	(
		[TRIGGER_ID] 
	) ON [PRIMARY]
GO

 CREATE INDEX [IX_TRIGGER] ON [dbo].[TRIGGER_STORE]([TRIGGER_NAME]) ON [PRIMARY]
GO

PRINT 'Creating foreign key constraint(s) for table CONTEXT_CONTAINER...'
GO
ALTER TABLE [dbo].[CONTEXT_CONTAINER] ADD
	CONSTRAINT [FK_CONTEXT_CONTAINER_EMAIL_BOX] FOREIGN KEY
(
		[EMAILBOX]
) REFERENCES [dbo].[EMAIL_BOX] (
		[EMAILBOX_ID]
)
GO

PRINT 'Creating foreign key constraint(s) for table EMAIL...'
GO
ALTER TABLE [dbo].[EMAIL] ADD
	CONSTRAINT [FK_EMAIL_CONTEXT_CONTAINER] FOREIGN KEY
(
		[CONTEXT_CONTAINER]
) REFERENCES [dbo].[CONTEXT_CONTAINER] (
		[CONTEXT_CONTAINER_ID]
)
GO

PRINT 'Creating foreign key constraint(s) for table TRIGGER_STORE...'
GO
ALTER TABLE [dbo].[TRIGGER_STORE] ADD
	CONSTRAINT [FK_TRIGGER_STORE_EMAIL_BOX] FOREIGN KEY
(
		[EMAILBOX]
) REFERENCES [dbo].[EMAIL_BOX] (
		[EMAILBOX_ID]
)
GO
