  CREATE TABLE "EMAIL_BOX" 
   (	"EMAILBOX_ID" NVARCHAR2(50) NOT NULL ENABLE, 
	"BOX_NAME" NVARCHAR2(50) NOT NULL ENABLE, 
	"HOST" NVARCHAR2(150) NOT NULL ENABLE, 
	"BOX_TYPE" NVARCHAR2(50) NOT NULL ENABLE, 
	"CONFIGURATION" NCLOB, 
	 CONSTRAINT "PK_EMAIL_BOX" PRIMARY KEY ("EMAILBOX_ID"),
	 CONSTRAINT "IX_EMAIL_BOX" UNIQUE ("BOX_NAME")
   );

  CREATE TABLE CONTEXT_CONTAINER 
   (	"CONTEXT_CONTAINER_ID" NVARCHAR2(50) NOT NULL ENABLE, 
	"EMAILBOX" NVARCHAR2(50) NOT NULL ENABLE, 
	"PROCESSING_STATUS" NVARCHAR2(30) NOT NULL ENABLE, 
	"STATUS_INFORMATION" NCLOB, 
	"TRIGGER_DEFINITION" NCLOB, 
	"CREATE_DATE" DATE NOT NULL ENABLE, 
	"STATUS_CHANGE_DATE" DATE NOT NULL ENABLE, 
	"COMPLETE_DATE" DATE, 
	 CONSTRAINT "PK_CONTEXT_CONTAINER" PRIMARY KEY ("CONTEXT_CONTAINER_ID"), 
	 CONSTRAINT "FK_CONTEXT_CONTAINER_EMAIL_BOX" FOREIGN KEY ("EMAILBOX") REFERENCES "EMAIL_BOX" ("EMAILBOX_ID") ENABLE
   );

  CREATE TABLE "EMAIL" 
   (	"EMAIL_ID" NVARCHAR2(50) NOT NULL ENABLE, 
	"CONTEXT_CONTAINER" NVARCHAR2(50) NOT NULL ENABLE, 
	"SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"SEND_DATE" DATE, 
	"RECEIVE_DATE" DATE, 
	"FROM_ADDRESS" NVARCHAR2(200), 
	"TO_ADDRESS" NVARCHAR2(200), 
	"SUBJECT" NVARCHAR2(200), 
	"CONTENT" NCLOB, 
	 CONSTRAINT "PK_EMAIL_DETAIL" PRIMARY KEY ("EMAIL_ID"),
	 CONSTRAINT "FK_EMAIL_CONTEXT_CONTAINER" FOREIGN KEY ("CONTEXT_CONTAINER")
	  REFERENCES "CONTEXT_CONTAINER" ("CONTEXT_CONTAINER_ID") ENABLE
   );
 
  CREATE TABLE "TRIGGER_STORE" 
   (	"TRIGGER_ID" NVARCHAR2(50) NOT NULL ENABLE, 
	"EMAILBOX" NVARCHAR2(50) NOT NULL ENABLE, 
	"TRIGGER_NAME" NVARCHAR2(150), 
	"CONTENT" NCLOB, 
	 CONSTRAINT "PK_TRIGGER_STORE" PRIMARY KEY ("TRIGGER_ID"),
	 CONSTRAINT "FK_TRIGGER_STORE_EMAIL_BOX" FOREIGN KEY ("EMAILBOX") REFERENCES "EMAIL_BOX" ("EMAILBOX_ID") ENABLE
   ) ;
 
  CREATE INDEX "IX_TRIGGER" ON "TRIGGER_STORE" ("TRIGGER_NAME");
  CREATE INDEX "IX_CONTEXT_CONTAINER_EMAIL_BOX" ON "CONTEXT_CONTAINER" ("EMAILBOX");
  CREATE INDEX "IX_CONTEXT_CONTAINER_STATUS" ON "CONTEXT_CONTAINER" ("PROCESSING_STATUS");
 
