/*
 * This class has been generated by the Code Generator
 */

/**
 * Copyright 2005 Cordys R&D B.V. 
 * 
 * This file is part of the Cordys SAP Connector. 
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 /**
 * Copyright 2005 Cordys R&D B.V. 
 * 
 * This file is part of the Cordys SAP Connector. 
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 package com.cordys.coe.ac.emailio.objects;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;

/**
 * DOCUMENTME.
 *
 * @author  $author$
 */
public abstract class EmailBoxBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    /**
     * tags used in the XML document.
     */
    public static final String ATTR_Name = "Name";
    /**
     * DOCUMENTME.
     */
    public static final String ATTR_Host = "Host";
    /**
     * DOCUMENTME.
     */
    public static final String ATTR_PollInterval = "PollInterval";
    /**
     * DOCUMENTME.
     */
    public static final String ATTR_Port = "Port";
    /**
     * DOCUMENTME.
     */
    public static final String ATTR_Username = "Username";
    /**
     * DOCUMENTME.
     */
    public static final String ATTR_Type = "Type";
    /**
     * DOCUMENTME.
     */
    public static final String ATTR_Configuration = "Configuration";
    /**
     * DOCUMENTME.
     */
    private static ClassInfo s_classInfo = null;

    /**
     * Creates a new EmailBoxBase object.
     *
     * @param  config  DOCUMENTME
     */
    public EmailBoxBase(BusObjectConfig config)
    {
        super(config);
    }

    /**
     * DOCUMENTME.
     *
     * @return  DOCUMENTME
     */
    public static ClassInfo _getClassInfo()
    {
        if (s_classInfo == null)
        {
            s_classInfo = newClassInfo(EmailBox.class);
            s_classInfo.setUIDElements(new String[] { ATTR_Name });

            {
                AttributeInfo ai = new AttributeInfo(ATTR_Name);
                ai.setJavaName("Name");
                ai.setAttributeClass(String.class);
                ai.setChangeability(AttributeInfo.CHANGEABILITY_FROZEN);
                s_classInfo.addAttributeInfo(ai);
            }

            {
                AttributeInfo ai = new AttributeInfo(ATTR_Host);
                ai.setJavaName("Host");
                ai.setAttributeClass(String.class);
                ai.setChangeability(AttributeInfo.CHANGEABILITY_FROZEN);
                s_classInfo.addAttributeInfo(ai);
            }

            {
                AttributeInfo ai = new AttributeInfo(ATTR_PollInterval);
                ai.setJavaName("PollInterval");
                ai.setAttributeClass(int.class);
                ai.setChangeability(AttributeInfo.CHANGEABILITY_FROZEN);

                NumberValidator v = new NumberValidator(ATTR_PollInterval);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }

            {
                AttributeInfo ai = new AttributeInfo(ATTR_Port);
                ai.setJavaName("Port");
                ai.setAttributeClass(int.class);
                ai.setChangeability(AttributeInfo.CHANGEABILITY_FROZEN);

                NumberValidator v = new NumberValidator(ATTR_Port);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }

            {
                AttributeInfo ai = new AttributeInfo(ATTR_Username);
                ai.setJavaName("Username");
                ai.setAttributeClass(String.class);
                ai.setChangeability(AttributeInfo.CHANGEABILITY_FROZEN);
                s_classInfo.addAttributeInfo(ai);
            }

            {
                AttributeInfo ai = new AttributeInfo(ATTR_Type);
                ai.setJavaName("Type");
                ai.setAttributeClass(String.class);
                ai.setChangeability(AttributeInfo.CHANGEABILITY_FROZEN);
                s_classInfo.addAttributeInfo(ai);
            }

            {
                AttributeInfo ai = new AttributeInfo(ATTR_Configuration);
                ai.setJavaName("Configuration");
                ai.setAttributeClass(String.class);
                ai.setChangeability(AttributeInfo.CHANGEABILITY_FROZEN);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    /**
     * DOCUMENTME.
     *
     * @return  DOCUMENTME
     */
    public String getConfiguration()
    {
        return getStringProperty(ATTR_Configuration);
    }

    /**
     * DOCUMENTME.
     *
     * @return  DOCUMENTME
     */
    public String getHost()
    {
        return getStringProperty(ATTR_Host);
    }

    /**
     * DOCUMENTME.
     *
     * @return  DOCUMENTME
     */
    public String getName()
    {
        return getStringProperty(ATTR_Name);
    }

    /**
     * DOCUMENTME.
     *
     * @return  DOCUMENTME
     */
    public int getPollInterval()
    {
        return getIntProperty(ATTR_PollInterval);
    }

    /**
     * DOCUMENTME.
     *
     * @return  DOCUMENTME
     */
    public int getPort()
    {
        return getIntProperty(ATTR_Port);
    }

    /**
     * DOCUMENTME.
     *
     * @return  DOCUMENTME
     */
    public String getType()
    {
        return getStringProperty(ATTR_Type);
    }

    /**
     * DOCUMENTME.
     *
     * @return  DOCUMENTME
     */
    public String getUsername()
    {
        return getStringProperty(ATTR_Username);
    }

    /**
     * DOCUMENTME.
     *
     * @param  value  DOCUMENTME
     */
    public void setConfiguration(String value)
    {
        setProperty(ATTR_Configuration, value, 0);
    }

    /**
     * DOCUMENTME.
     *
     * @param  value  DOCUMENTME
     */
    public void setHost(String value)
    {
        setProperty(ATTR_Host, value, 0);
    }

    /**
     * DOCUMENTME.
     *
     * @param  value  DOCUMENTME
     */
    public void setName(String value)
    {
        setProperty(ATTR_Name, value, 0);
    }

    /**
     * DOCUMENTME.
     *
     * @param  value  DOCUMENTME
     */
    public void setPollInterval(int value)
    {
        setProperty(ATTR_PollInterval, value, 0);
    }

    /**
     * DOCUMENTME.
     *
     * @param  value  DOCUMENTME
     */
    public void setPort(int value)
    {
        setProperty(ATTR_Port, value, 0);
    }

    /**
     * DOCUMENTME.
     *
     * @param  value  DOCUMENTME
     */
    public void setType(String value)
    {
        setProperty(ATTR_Type, value, 0);
    }

    /**
     * DOCUMENTME.
     *
     * @param  value  DOCUMENTME
     */
    public void setUsername(String value)
    {
        setProperty(ATTR_Username, value, 0);
    }
}
