package com.cordys.coe.ac.emailio.tools;

import java.io.File;
import java.io.FilenameFilter;

import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * This tool allows a user to resend a message exactly as it was received. The only things that can
 * be changed are the from and to address.
 *
 * @author  pgussow
 */
public class ResendEmails extends javax.swing.JFrame
{
    /**
     * DOCUMENTME.
     */
    private File m_fFolder = new File(".");

    /**
     * DOCUMENTME.
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JFileChooser m_fcChooser;
    /**
     * DOCUMENTME.
     */
    javax.swing.JList m_lFiles;
    /**
     * DOCUMENTME.
     */
    javax.swing.JTextField m_tFolder;
    /**
     * DOCUMENTME.
     */
    javax.swing.JPasswordField m_tPassword;
    /**
     * DOCUMENTME.
     */
    javax.swing.JTextField m_tPort;
    /**
     * DOCUMENTME.
     */
    javax.swing.JTextField m_tServer;
    /**
     * DOCUMENTME.
     */
    javax.swing.JTextField m_tUsername;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form ResendEmails.
     */
    public ResendEmails()
    {
        initComponents();
    }

    /**
     * DOCUMENTME.
     *
     * @param  args  the command line arguments
     */
    public static void main(String[] args)
    {
        java.awt.EventQueue.invokeLater(new Runnable()
            {
                public void run()
                {
                    new ResendEmails().setVisible(true);
                }
            });
    }

    /**
     * DOCUMENTME.
     *
     * @param  evt  DOCUMENTME
     */
    private void browseFolder(java.awt.event.ActionEvent evt) //GEN-FIRST:event_browseFolder
    {
        if (m_fcChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            m_fFolder = m_fcChooser.getSelectedFile();
            loadEmailFiles();
        }
    } //GEN-LAST:event_browseFolder

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        m_fcChooser = new javax.swing.JFileChooser();

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        m_tServer = new javax.swing.JTextField();

        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        m_tPort = new javax.swing.JTextField();

        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        m_tUsername = new javax.swing.JTextField();

        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        m_tPassword = new javax.swing.JPasswordField();

        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        m_tFolder = new javax.swing.JTextField();

        javax.swing.JButton bBrowse = new javax.swing.JButton();
        javax.swing.JSplitPane jSplitPane1 = new javax.swing.JSplitPane();
        javax.swing.JPanel pMailFiles = new javax.swing.JPanel();
        javax.swing.JButton bRefresh = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        m_lFiles = new javax.swing.JList();

        javax.swing.JTabbedPane jTabbedPane1 = new javax.swing.JTabbedPane();
        javax.swing.JPanel pMailMessage = new javax.swing.JPanel();
        javax.swing.JButton bResend = new javax.swing.JButton();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JTextField m_tFrom = new javax.swing.JTextField();
        javax.swing.JTextField m_tTo = new javax.swing.JTextField();
        javax.swing.JTextField m_tSubject = new javax.swing.JTextField();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        javax.swing.JTextArea m_taOriginal = new javax.swing.JTextArea();
        javax.swing.JButton bLocalTest = new javax.swing.JButton();
        javax.swing.JPanel pLocalTrigger = new javax.swing.JPanel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
        javax.swing.JTextArea m_taTrigger = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Resend emails");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(" SMTP Server details "));

        m_fcChooser.setFileFilter(new FileNameExtensionFilter("Email files", "eml"));
        m_fcChooser.setCurrentDirectory(new File("."));
        m_fcChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Server:");

        jLabel2.setText("Port:");

        m_tPort.setText("25");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Username:");

        jLabel5.setText("Password:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Source folder:");

        bBrowse.setText("...");
        bBrowse.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    browseFolder(evt);
                }
            });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout
                                                                           .Alignment.LEADING)
                                         .addGroup(jPanel1Layout.createSequentialGroup()
                                                   .addContainerGap().addGroup(jPanel1Layout
                                                                               .createParallelGroup(javax
                                                                                                    .swing
                                                                                                    .GroupLayout
                                                                                                    .Alignment.LEADING,
                                                                                                    false)
                                                                               .addComponent(jLabel6,
                                                                                             javax
                                                                                             .swing
                                                                                             .GroupLayout.DEFAULT_SIZE,
                                                                                             javax
                                                                                             .swing
                                                                                             .GroupLayout.DEFAULT_SIZE,
                                                                                             Short.MAX_VALUE)
                                                                               .addComponent(jLabel4,
                                                                                             javax
                                                                                             .swing
                                                                                             .GroupLayout.DEFAULT_SIZE,
                                                                                             javax
                                                                                             .swing
                                                                                             .GroupLayout.DEFAULT_SIZE,
                                                                                             Short.MAX_VALUE)
                                                                               .addComponent(jLabel1,
                                                                                             javax
                                                                                             .swing
                                                                                             .GroupLayout.DEFAULT_SIZE,
                                                                                             javax
                                                                                             .swing
                                                                                             .GroupLayout.DEFAULT_SIZE,
                                                                                             Short.MAX_VALUE))
                                                   .addPreferredGap(javax.swing.LayoutStyle
                                                                    .ComponentPlacement.RELATED)
                                                   .addGroup(jPanel1Layout.createParallelGroup(javax
                                                                                               .swing
                                                                                               .GroupLayout
                                                                                               .Alignment.LEADING)
                                                             .addGroup(jPanel1Layout
                                                                       .createSequentialGroup()
                                                                       .addComponent(m_tFolder,
                                                                                     javax.swing
                                                                                     .GroupLayout.DEFAULT_SIZE,
                                                                                     653,
                                                                                     Short.MAX_VALUE)
                                                                       .addPreferredGap(javax.swing
                                                                                        .LayoutStyle
                                                                                        .ComponentPlacement.RELATED)
                                                                       .addComponent(bBrowse,
                                                                                     javax.swing
                                                                                     .GroupLayout.PREFERRED_SIZE,
                                                                                     21,
                                                                                     javax.swing
                                                                                     .GroupLayout.PREFERRED_SIZE))
                                                             .addGroup(jPanel1Layout
                                                                       .createSequentialGroup()
                                                                       .addComponent(m_tServer,
                                                                                     javax.swing
                                                                                     .GroupLayout.DEFAULT_SIZE,
                                                                                     606,
                                                                                     Short.MAX_VALUE)
                                                                       .addPreferredGap(javax.swing
                                                                                        .LayoutStyle
                                                                                        .ComponentPlacement.RELATED)
                                                                       .addComponent(jLabel2)
                                                                       .addPreferredGap(javax.swing
                                                                                        .LayoutStyle
                                                                                        .ComponentPlacement.UNRELATED)
                                                                       .addComponent(m_tPort,
                                                                                     javax.swing
                                                                                     .GroupLayout.PREFERRED_SIZE,
                                                                                     36,
                                                                                     javax.swing
                                                                                     .GroupLayout.PREFERRED_SIZE))
                                                             .addGroup(jPanel1Layout
                                                                       .createSequentialGroup()
                                                                       .addComponent(m_tUsername,
                                                                                     javax.swing
                                                                                     .GroupLayout.PREFERRED_SIZE,
                                                                                     198,
                                                                                     javax.swing
                                                                                     .GroupLayout.PREFERRED_SIZE)
                                                                       .addPreferredGap(javax.swing
                                                                                        .LayoutStyle
                                                                                        .ComponentPlacement.RELATED)
                                                                       .addComponent(jLabel5)
                                                                       .addPreferredGap(javax.swing
                                                                                        .LayoutStyle
                                                                                        .ComponentPlacement.RELATED)
                                                                       .addComponent(m_tPassword,
                                                                                     javax.swing
                                                                                     .GroupLayout.DEFAULT_SIZE,
                                                                                     424,
                                                                                     Short.MAX_VALUE)))
                                                   .addContainerGap()));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout
                                                                         .Alignment.LEADING)
                                       .addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
                                                                                                .createParallelGroup(javax
                                                                                                                     .swing
                                                                                                                     .GroupLayout
                                                                                                                     .Alignment.BASELINE)
                                                                                                .addComponent(m_tPort,
                                                                                                              javax
                                                                                                              .swing
                                                                                                              .GroupLayout.PREFERRED_SIZE,
                                                                                                              javax
                                                                                                              .swing
                                                                                                              .GroupLayout.DEFAULT_SIZE,
                                                                                                              javax
                                                                                                              .swing
                                                                                                              .GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabel2)
                                                                                                .addComponent(m_tServer,
                                                                                                              javax
                                                                                                              .swing
                                                                                                              .GroupLayout.PREFERRED_SIZE,
                                                                                                              javax
                                                                                                              .swing
                                                                                                              .GroupLayout.DEFAULT_SIZE,
                                                                                                              javax
                                                                                                              .swing
                                                                                                              .GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabel1))
                                                 .addPreferredGap(javax.swing.LayoutStyle
                                                                  .ComponentPlacement.RELATED)
                                                 .addGroup(jPanel1Layout.createParallelGroup(javax
                                                                                             .swing
                                                                                             .GroupLayout
                                                                                             .Alignment.BASELINE)
                                                           .addComponent(jLabel5).addComponent(m_tPassword,
                                                                                               javax
                                                                                               .swing
                                                                                               .GroupLayout.PREFERRED_SIZE,
                                                                                               javax
                                                                                               .swing
                                                                                               .GroupLayout.DEFAULT_SIZE,
                                                                                               javax
                                                                                               .swing
                                                                                               .GroupLayout.PREFERRED_SIZE)
                                                           .addComponent(m_tUsername,
                                                                         javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                         javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                         javax.swing.GroupLayout.PREFERRED_SIZE)
                                                           .addComponent(jLabel4)).addPreferredGap(javax
                                                                                                   .swing
                                                                                                   .LayoutStyle
                                                                                                   .ComponentPlacement.RELATED)
                                                 .addGroup(jPanel1Layout.createParallelGroup(javax
                                                                                             .swing
                                                                                             .GroupLayout
                                                                                             .Alignment.BASELINE)
                                                           .addComponent(jLabel6).addComponent(bBrowse)
                                                           .addComponent(m_tFolder,
                                                                         javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                         javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                         javax.swing.GroupLayout.PREFERRED_SIZE))
                                                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                  Short.MAX_VALUE)));

        jSplitPane1.setDividerLocation(149);

        bRefresh.setText("Refresh");
        bRefresh.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    refreshFiles(evt);
                }
            });

        m_lFiles.setModel(new javax.swing.AbstractListModel()
            {
                String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

                @Override public int getSize()
                {
                    return strings.length;
                }

                @Override public Object getElementAt(int i)
                {
                    return strings[i];
                }
            });
        jScrollPane1.setViewportView(m_lFiles);

        javax.swing.GroupLayout pMailFilesLayout = new javax.swing.GroupLayout(pMailFiles);
        pMailFiles.setLayout(pMailFilesLayout);
        pMailFilesLayout.setHorizontalGroup(pMailFilesLayout.createParallelGroup(javax.swing
                                                                                 .GroupLayout
                                                                                 .Alignment.LEADING)
                                            .addComponent(bRefresh,
                                                          javax.swing.GroupLayout.DEFAULT_SIZE, 148,
                                                          Short.MAX_VALUE).addComponent(jScrollPane1,
                                                                                        javax.swing
                                                                                        .GroupLayout.DEFAULT_SIZE,
                                                                                        148,
                                                                                        Short.MAX_VALUE));
        pMailFilesLayout.setVerticalGroup(pMailFilesLayout.createParallelGroup(javax.swing
                                                                               .GroupLayout
                                                                               .Alignment.LEADING)
                                          .addGroup(pMailFilesLayout.createSequentialGroup()
                                                    .addComponent(bRefresh).addPreferredGap(javax
                                                                                            .swing
                                                                                            .LayoutStyle
                                                                                            .ComponentPlacement.RELATED)
                                                    .addComponent(jScrollPane1,
                                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                  208, Short.MAX_VALUE)));

        jSplitPane1.setLeftComponent(pMailFiles);

        bResend.setText("Resend");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("From:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("To:");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Subject:");

        m_taOriginal.setColumns(20);
        m_taOriginal.setRows(5);
        jScrollPane2.setViewportView(m_taOriginal);

        bLocalTest.setText("Local test");

        javax.swing.GroupLayout pMailMessageLayout = new javax.swing.GroupLayout(pMailMessage);
        pMailMessage.setLayout(pMailMessageLayout);
        pMailMessageLayout.setHorizontalGroup(pMailMessageLayout.createParallelGroup(javax.swing
                                                                                     .GroupLayout
                                                                                     .Alignment.LEADING)
                                              .addGroup(pMailMessageLayout.createSequentialGroup()
                                                        .addGroup(pMailMessageLayout
                                                                  .createParallelGroup(javax.swing
                                                                                       .GroupLayout
                                                                                       .Alignment.LEADING)
                                                                  .addGroup(pMailMessageLayout
                                                                            .createSequentialGroup()
                                                                            .addComponent(bResend)
                                                                            .addPreferredGap(javax
                                                                                             .swing
                                                                                             .LayoutStyle
                                                                                             .ComponentPlacement.RELATED)
                                                                            .addComponent(bLocalTest))
                                                                  .addGroup(pMailMessageLayout
                                                                            .createSequentialGroup()
                                                                            .addContainerGap()
                                                                            .addGroup(pMailMessageLayout
                                                                                      .createParallelGroup(javax
                                                                                                           .swing
                                                                                                           .GroupLayout
                                                                                                           .Alignment.LEADING)
                                                                                      .addComponent(jScrollPane2,
                                                                                                    javax
                                                                                                    .swing
                                                                                                    .GroupLayout.DEFAULT_SIZE,
                                                                                                    604,
                                                                                                    Short.MAX_VALUE)
                                                                                      .addGroup(pMailMessageLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(pMailMessageLayout
                                                                                                          .createParallelGroup(javax
                                                                                                                               .swing
                                                                                                                               .GroupLayout
                                                                                                                               .Alignment.LEADING,
                                                                                                                               false)
                                                                                                          .addComponent(jLabel9,
                                                                                                                        javax
                                                                                                                        .swing
                                                                                                                        .GroupLayout.DEFAULT_SIZE,
                                                                                                                        javax
                                                                                                                        .swing
                                                                                                                        .GroupLayout.DEFAULT_SIZE,
                                                                                                                        Short.MAX_VALUE)
                                                                                                          .addComponent(jLabel8,
                                                                                                                        javax
                                                                                                                        .swing
                                                                                                                        .GroupLayout.DEFAULT_SIZE,
                                                                                                                        javax
                                                                                                                        .swing
                                                                                                                        .GroupLayout.DEFAULT_SIZE,
                                                                                                                        Short.MAX_VALUE)
                                                                                                          .addComponent(jLabel7))
                                                                                                .addPreferredGap(javax
                                                                                                                 .swing
                                                                                                                 .LayoutStyle
                                                                                                                 .ComponentPlacement.RELATED)
                                                                                                .addGroup(pMailMessageLayout
                                                                                                          .createParallelGroup(javax
                                                                                                                               .swing
                                                                                                                               .GroupLayout
                                                                                                                               .Alignment.LEADING)
                                                                                                          .addComponent(m_tTo,
                                                                                                                        javax
                                                                                                                        .swing
                                                                                                                        .GroupLayout.DEFAULT_SIZE,
                                                                                                                        560,
                                                                                                                        Short.MAX_VALUE)
                                                                                                          .addComponent(m_tFrom,
                                                                                                                        javax
                                                                                                                        .swing
                                                                                                                        .GroupLayout.DEFAULT_SIZE,
                                                                                                                        560,
                                                                                                                        Short.MAX_VALUE)
                                                                                                          .addComponent(m_tSubject,
                                                                                                                        javax
                                                                                                                        .swing
                                                                                                                        .GroupLayout.DEFAULT_SIZE,
                                                                                                                        560,
                                                                                                                        Short.MAX_VALUE))))))
                                                        .addContainerGap()));
        pMailMessageLayout.setVerticalGroup(pMailMessageLayout.createParallelGroup(javax.swing
                                                                                   .GroupLayout
                                                                                   .Alignment.LEADING)
                                            .addGroup(pMailMessageLayout.createSequentialGroup()
                                                      .addGroup(pMailMessageLayout
                                                                .createParallelGroup(javax.swing
                                                                                     .GroupLayout
                                                                                     .Alignment.BASELINE)
                                                                .addComponent(bResend).addComponent(bLocalTest))
                                                      .addPreferredGap(javax.swing.LayoutStyle
                                                                       .ComponentPlacement.RELATED)
                                                      .addGroup(pMailMessageLayout
                                                                .createParallelGroup(javax.swing
                                                                                     .GroupLayout
                                                                                     .Alignment.BASELINE)
                                                                .addComponent(m_tFrom,
                                                                              javax.swing
                                                                              .GroupLayout.PREFERRED_SIZE,
                                                                              javax.swing
                                                                              .GroupLayout.DEFAULT_SIZE,
                                                                              javax.swing
                                                                              .GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel7))
                                                      .addPreferredGap(javax.swing.LayoutStyle
                                                                       .ComponentPlacement.RELATED)
                                                      .addGroup(pMailMessageLayout
                                                                .createParallelGroup(javax.swing
                                                                                     .GroupLayout
                                                                                     .Alignment.BASELINE)
                                                                .addComponent(m_tTo,
                                                                              javax.swing
                                                                              .GroupLayout.PREFERRED_SIZE,
                                                                              javax.swing
                                                                              .GroupLayout.DEFAULT_SIZE,
                                                                              javax.swing
                                                                              .GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel8))
                                                      .addPreferredGap(javax.swing.LayoutStyle
                                                                       .ComponentPlacement.RELATED)
                                                      .addGroup(pMailMessageLayout
                                                                .createParallelGroup(javax.swing
                                                                                     .GroupLayout
                                                                                     .Alignment.BASELINE)
                                                                .addComponent(m_tSubject,
                                                                              javax.swing
                                                                              .GroupLayout.PREFERRED_SIZE,
                                                                              javax.swing
                                                                              .GroupLayout.DEFAULT_SIZE,
                                                                              javax.swing
                                                                              .GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel9))
                                                      .addPreferredGap(javax.swing.LayoutStyle
                                                                       .ComponentPlacement.RELATED)
                                                      .addComponent(jScrollPane2,
                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                    94, Short.MAX_VALUE)
                                                      .addContainerGap()));

        jTabbedPane1.addTab("Mail message", pMailMessage);

        jLabel3.setText("You can paste the definition of an email box in here and it's triggers");

        jLabel10.setText("Then press the 'Local test' button to execute the trigger on the currently loaded mail.");

        m_taTrigger.setColumns(20);
        m_taTrigger.setRows(5);
        jScrollPane3.setViewportView(m_taTrigger);

        javax.swing.GroupLayout pLocalTriggerLayout = new javax.swing.GroupLayout(pLocalTrigger);
        pLocalTrigger.setLayout(pLocalTriggerLayout);
        pLocalTriggerLayout.setHorizontalGroup(pLocalTriggerLayout.createParallelGroup(javax.swing
                                                                                       .GroupLayout
                                                                                       .Alignment.LEADING)
                                               .addComponent(jLabel3,
                                                             javax.swing.GroupLayout.DEFAULT_SIZE,
                                                             624, Short.MAX_VALUE).addComponent(jLabel10,
                                                                                                javax
                                                                                                .swing
                                                                                                .GroupLayout.DEFAULT_SIZE,
                                                                                                624,
                                                                                                Short.MAX_VALUE)
                                               .addComponent(jScrollPane3,
                                                             javax.swing.GroupLayout.DEFAULT_SIZE,
                                                             624, Short.MAX_VALUE));
        pLocalTriggerLayout.setVerticalGroup(pLocalTriggerLayout.createParallelGroup(javax.swing
                                                                                     .GroupLayout
                                                                                     .Alignment.LEADING)
                                             .addGroup(pLocalTriggerLayout.createSequentialGroup()
                                                       .addComponent(jLabel3).addPreferredGap(javax
                                                                                              .swing
                                                                                              .LayoutStyle
                                                                                              .ComponentPlacement.RELATED)
                                                       .addComponent(jLabel10).addPreferredGap(javax
                                                                                               .swing
                                                                                               .LayoutStyle
                                                                                               .ComponentPlacement.RELATED)
                                                       .addComponent(jScrollPane3,
                                                                     javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                     172, Short.MAX_VALUE)));

        jTabbedPane1.addTab("EmailBox", pLocalTrigger);

        jSplitPane1.setRightComponent(jTabbedPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                            layout.createSequentialGroup().addContainerGap()
                                            .addGroup(layout.createParallelGroup(javax.swing
                                                                                 .GroupLayout
                                                                                 .Alignment.TRAILING)
                                                      .addComponent(jSplitPane1,
                                                                    javax.swing.GroupLayout
                                                                    .Alignment.LEADING,
                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                    784, Short.MAX_VALUE)
                                                      .addComponent(jPanel1,
                                                                    javax.swing.GroupLayout
                                                                    .Alignment.LEADING,
                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                    Short.MAX_VALUE))
                                            .addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addComponent(jPanel1,
                                                                                      javax.swing
                                                                                      .GroupLayout.PREFERRED_SIZE,
                                                                                      javax.swing
                                                                                      .GroupLayout.DEFAULT_SIZE,
                                                                                      javax.swing
                                                                                      .GroupLayout.PREFERRED_SIZE)
                                          .addPreferredGap(javax.swing.LayoutStyle
                                                           .ComponentPlacement.RELATED)
                                          .addComponent(jSplitPane1,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 239,
                                                        Short.MAX_VALUE).addContainerGap()));

        pack();
    } // </editor-fold>//GEN-END:initComponents

    /**
     * This method loads all .eml files from the given location.
     */
    private void loadEmailFiles()
    {
        String[] asFiles;
        DefaultListModel dlm;

        if (m_fFolder != null)
        {
            asFiles = m_fFolder.list(new FilenameFilter()
                    {
                        public boolean accept(File dir, String sName)
                        {
                            return sName.endsWith(".eml");
                        }
                    });

            dlm = (DefaultListModel) m_lFiles.getModel();
            dlm.removeAllElements();

            for (String sFile : asFiles)
            {
                dlm.addElement(new FileWrapper(new File(m_fFolder, sFile)));
            }
        }
    }

    /**
     * DOCUMENTME.
     *
     * @param  evt  DOCUMENTME
     */
    private void refreshFiles(java.awt.event.ActionEvent evt) //GEN-FIRST:event_refreshFiles
    {
        loadEmailFiles();
    } //GEN-LAST:event_refreshFiles

    /**
     * DOCUMENTME.
     *
     * @author  $author$
     */
    private class FileWrapper
    {
        /**
         * DOCUMENTME.
         */
        private File m_f;

        /**
         * Creates a new FileWrapper object.
         *
         * @param  f  DOCUMENTME
         */
        public FileWrapper(File f)
        {
            m_f = f;
        }

        /**
         * @see  java.lang.Object#toString()
         */
        @Override public String toString()
        {
            return m_f.getName();
        }
    }
}
