/*
 * This class has been generated by the Code Generator
 */

/**
 * Copyright 2005 Cordys R&D B.V. 
 * 
 * This file is part of the Cordys SAP Connector. 
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 /**
 * Copyright 2005 Cordys R&D B.V. 
 * 
 * This file is part of the Cordys SAP Connector. 
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 package com.cordys.coe.ac.emailio.objects;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;

/**
 * DOCUMENTME.
 *
 * @author  $author$
 */
public abstract class EmailMessageBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    /**
     * tags used in the XML document.
     */
    public static final String ATTR_ID = "ID";
    /**
     * DOCUMENTME.
     */
    public static final String ATTR_SequenceID = "SequenceID";
    /**
     * DOCUMENTME.
     */
    public static final String ATTR_ContextContainerID = "ContextContainerID";
    /**
     * DOCUMENTME.
     */
    public static final String ATTR_From = "From";
    /**
     * DOCUMENTME.
     */
    public static final String ATTR_To = "To";
    /**
     * DOCUMENTME.
     */
    public static final String ATTR_Subject = "Subject";
    /**
     * DOCUMENTME.
     */
    public static final String ATTR_SendDate = "SendDate";
    /**
     * DOCUMENTME.
     */
    public static final String ATTR_ReceiveDate = "ReceiveDate";
    /**
     * DOCUMENTME.
     */
    public static final String ATTR_RawContent = "RawContent";
    /**
     * DOCUMENTME.
     */
    private static ClassInfo s_classInfo = null;

    /**
     * Creates a new EmailMessageBase object.
     *
     * @param  config  DOCUMENTME
     */
    public EmailMessageBase(BusObjectConfig config)
    {
        super(config);
    }

    /**
     * DOCUMENTME.
     *
     * @return  DOCUMENTME
     */
    public static ClassInfo _getClassInfo()
    {
        if (s_classInfo == null)
        {
            s_classInfo = newClassInfo(EmailMessage.class);
            s_classInfo.setUIDElements(new String[] { ATTR_ID });

            {
                AttributeInfo ai = new AttributeInfo(ATTR_ID);
                ai.setJavaName("ID");
                ai.setAttributeClass(String.class);
                ai.setChangeability(AttributeInfo.CHANGEABILITY_FROZEN);
                s_classInfo.addAttributeInfo(ai);
            }

            {
                AttributeInfo ai = new AttributeInfo(ATTR_SequenceID);
                ai.setJavaName("SequenceID");
                ai.setAttributeClass(long.class);
                ai.setChangeability(AttributeInfo.CHANGEABILITY_FROZEN);

                NumberValidator v = new NumberValidator(ATTR_SequenceID);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }

            {
                AttributeInfo ai = new AttributeInfo(ATTR_ContextContainerID);
                ai.setJavaName("ContextContainerID");
                ai.setAttributeClass(String.class);
                ai.setChangeability(AttributeInfo.CHANGEABILITY_FROZEN);
                s_classInfo.addAttributeInfo(ai);
            }

            {
                AttributeInfo ai = new AttributeInfo(ATTR_From);
                ai.setJavaName("From");
                ai.setAttributeClass(String.class);
                ai.setChangeability(AttributeInfo.CHANGEABILITY_FROZEN);
                s_classInfo.addAttributeInfo(ai);
            }

            {
                AttributeInfo ai = new AttributeInfo(ATTR_To);
                ai.setJavaName("To");
                ai.setAttributeClass(String.class);
                ai.setChangeability(AttributeInfo.CHANGEABILITY_FROZEN);
                s_classInfo.addAttributeInfo(ai);
            }

            {
                AttributeInfo ai = new AttributeInfo(ATTR_Subject);
                ai.setJavaName("Subject");
                ai.setAttributeClass(String.class);
                ai.setChangeability(AttributeInfo.CHANGEABILITY_FROZEN);
                s_classInfo.addAttributeInfo(ai);
            }

            {
                AttributeInfo ai = new AttributeInfo(ATTR_SendDate);
                ai.setJavaName("SendDate");
                ai.setAttributeClass(java.util.Date.class);
                ai.setChangeability(AttributeInfo.CHANGEABILITY_FROZEN);
                s_classInfo.addAttributeInfo(ai);
            }

            {
                AttributeInfo ai = new AttributeInfo(ATTR_ReceiveDate);
                ai.setJavaName("ReceiveDate");
                ai.setAttributeClass(java.util.Date.class);
                ai.setChangeability(AttributeInfo.CHANGEABILITY_FROZEN);
                s_classInfo.addAttributeInfo(ai);
            }

            {
                AttributeInfo ai = new AttributeInfo(ATTR_RawContent);
                ai.setJavaName("RawContent");
                ai.setAttributeClass(String.class);
                ai.setChangeability(AttributeInfo.CHANGEABILITY_FROZEN);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    /**
     * DOCUMENTME.
     *
     * @return  DOCUMENTME
     */
    public String getContextContainerID()
    {
        return getStringProperty(ATTR_ContextContainerID);
    }

    /**
     * DOCUMENTME.
     *
     * @return  DOCUMENTME
     */
    public String getFrom()
    {
        return getStringProperty(ATTR_From);
    }

    /**
     * DOCUMENTME.
     *
     * @return  DOCUMENTME
     */
    public String getID()
    {
        return getStringProperty(ATTR_ID);
    }

    /**
     * DOCUMENTME.
     *
     * @return  DOCUMENTME
     */
    public String getRawContent()
    {
        return getStringProperty(ATTR_RawContent);
    }

    /**
     * DOCUMENTME.
     *
     * @return  DOCUMENTME
     */
    public java.util.Date getReceiveDate()
    {
        return getDateTimestampProperty(ATTR_ReceiveDate);
    }

    /**
     * DOCUMENTME.
     *
     * @return  DOCUMENTME
     */
    public java.util.Date getSendDate()
    {
        return getDateTimestampProperty(ATTR_SendDate);
    }

    /**
     * DOCUMENTME.
     *
     * @return  DOCUMENTME
     */
    public long getSequenceID()
    {
        return getLongProperty(ATTR_SequenceID);
    }

    /**
     * DOCUMENTME.
     *
     * @return  DOCUMENTME
     */
    public String getSubject()
    {
        return getStringProperty(ATTR_Subject);
    }

    /**
     * DOCUMENTME.
     *
     * @return  DOCUMENTME
     */
    public String getTo()
    {
        return getStringProperty(ATTR_To);
    }

    /**
     * DOCUMENTME.
     *
     * @param  value  DOCUMENTME
     */
    public void setContextContainerID(String value)
    {
        setProperty(ATTR_ContextContainerID, value, 0);
    }

    /**
     * DOCUMENTME.
     *
     * @param  value  DOCUMENTME
     */
    public void setFrom(String value)
    {
        setProperty(ATTR_From, value, 0);
    }

    /**
     * DOCUMENTME.
     *
     * @param  value  DOCUMENTME
     */
    public void setID(String value)
    {
        setProperty(ATTR_ID, value, 0);
    }

    /**
     * DOCUMENTME.
     *
     * @param  value  DOCUMENTME
     */
    public void setRawContent(String value)
    {
        setProperty(ATTR_RawContent, value, 0);
    }

    /**
     * DOCUMENTME.
     *
     * @param  value  DOCUMENTME
     */
    public void setReceiveDate(java.util.Date value)
    {
        setProperty(ATTR_ReceiveDate, value, 0);
    }

    /**
     * DOCUMENTME.
     *
     * @param  value  DOCUMENTME
     */
    public void setSendDate(java.util.Date value)
    {
        setProperty(ATTR_SendDate, value, 0);
    }

    /**
     * DOCUMENTME.
     *
     * @param  value  DOCUMENTME
     */
    public void setSequenceID(long value)
    {
        setProperty(ATTR_SequenceID, value, 0);
    }

    /**
     * DOCUMENTME.
     *
     * @param  value  DOCUMENTME
     */
    public void setSubject(String value)
    {
        setProperty(ATTR_Subject, value, 0);
    }

    /**
     * DOCUMENTME.
     *
     * @param  value  DOCUMENTME
     */
    public void setTo(String value)
    {
        setProperty(ATTR_To, value, 0);
    }
}
